version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: rustdb
      POSTGRES_PASSWORD: rustpwd
      POSTGRES_DB: db_content_snapshot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount the init-scripts directory
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
